# -*- coding: utf-8 -*-
"""Brain Tumor Detection using YOLOv8 variants.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZgF-VhfcjruyTYiOL08agajBQNN5FBhm
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import shutil
!pip install ultralytics
from ultralytics import YOLO

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5
# %cd yolov5
!pip install -r requirements.txt

import zipfile
import os
import shutil

# Define paths
drive_dataset_path = "/content/drive/MyDrive/brain tumor 2.v3i.yolov8.zip"
local_dataset_path = "/content/dataset"

# Create the local dataset directory if it doesn't exist
os.makedirs(local_dataset_path, exist_ok=True)

# Copy and extract dataset from Drive to local
print("Copying and extracting dataset from Drive to local...")
if os.path.exists(drive_dataset_path):
    try:
        with zipfile.ZipFile(drive_dataset_path, 'r') as zip_ref:
            zip_ref.extractall(local_dataset_path)
        print("Dataset extracted successfully!")

        # Check what we have
        print("\nDataset structure:")
        for item in os.listdir(local_dataset_path):
            item_path = os.path.join(local_dataset_path, item)
            if os.path.isdir(item_path):
                file_count = len(os.listdir(item_path))
                print(f"{item}/ - {file_count} items")
            else:
                print(f"{item}")

    except zipfile.BadZipFile:
        print("Error: The file is not a valid zip archive.")
    except Exception as e:
        print(f"An unexpected error occurred during extraction: {e}")
else:
    print("Dataset ZIP file not found in Drive!")

# Train YOLOv8n, YOLOv8s, YOLOv8m
models = ['yolov8n.pt', 'yolov8s.pt', 'yolov8m.pt']

for model_name in models:
    print(f"\n Training {model_name}...")

    model = YOLO(model_name)

    model.train(
        data=f'{local_dataset_path}/data.yaml',  # Uses your train/valid splits
        epochs=50,
        imgsz=640,
        batch=16,
        name=f"{model_name.replace('.pt', '')}_brain",
        save=True
    )

    print(f"{model_name} training completed!")

import os
from ultralytics import YOLO
import pandas as pd

results = {}

base_path = "/content/yolov5/runs/detect"

for folder in os.listdir(base_path):
    weight_path = os.path.join(base_path, folder, "weights", "best.pt")

    if os.path.exists(weight_path):
        print(f"🔍 Evaluating {folder}...")
        model = YOLO(weight_path)
        metrics = model.val()

        results[folder] = {
            "mAP50": metrics.box.map50,
            "mAP50-95": metrics.box.map,
            "Precision": metrics.box.mp,
            "Recall": metrics.box.mr,
            "Inference_Time_ms": sum(metrics.speed.values()) / len(metrics.speed),
            "Model_Size_MB": os.path.getsize(weight_path) / (1024 * 1024)
        }

comparison_df = pd.DataFrame(results).T
comparison_df
